packages:
  - "app"
  - "packages/*"

overrides:
  vite: "npm:rolldown-vite@latest"

catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  typescript: 5.9.2
  tsdown: ^0.12.9
  jotai: ^2.12.5

# 以下为性能优化
resolutionMode: lowest-direct
autoInstallPeers: true
preferOffline: true
hoist: false
childConcurrency: 12
