packages:
  - "app"
  - "packages/*"

catalog:
  react: ^19.1.0
  "@types/react": ^19.1.0
  react-dom: ^19.1.0
  typescript: 5.9.2
  tsdown: ^0.21.10
  jotai: ^2.12.5
  vitest: 4.1.5
  unplugin-original-class-name: ^1.0.1

allowBuilds:
  - "@swc/core"
  - bcrypt
  - esbuild
  - msw
  - nx
  - sharp

patchedDependencies:
  typescript: "patches/typescript.patch"
