extends "res://tests/next_layer_preview_smoke.gd"
func _run() -> void:
	root.size = Vector2i(1280,800)
	app = load("res://src/main/main.tscn").instantiate()
	root.add_child(app)
	await settle()
	app.get_node("UIOverlay/Welcome").hide()
	stage = app.tabs.get_current_stage()
	GraphPreferences.set_value("physics",false,false)
	stage.apply_preferences()
	var frame := make_node("分组顶部标题",Vector2.ZERO)
	var branch := make_node("下一层分支很长的名称需要省略",Vector2(-500,0),frame)
	var peer := make_node("另一条分支",Vector2(500,0),frame)
	var deep := make_node("不应出现的深层说明",Vector2(-1100,250),frame)
	stage.connect_entities(branch,deep)
	stage.connect_entities(deep,peer)
	stage.connect_entities(frame,peer)
	await zoom_to(2.0)
	var before := StageObjectRegistry.capture(stage)
	stage.camera.position = frame.aabb.get_center()
	stage.camera.target_position = stage.camera.position
	await zoom_to(.5)
	var overview := stage.group_overview
	var panel: Panel = overview._summaries[frame.get_instance_id()]
	var title: Label = panel.get_node("Title")
	var bounds := title.get_global_transform_with_canvas() * Rect2(Vector2.ZERO, title.size)
	var frame_bounds := panel.get_global_transform_with_canvas() * Rect2(Vector2.ZERO, panel.size)
	check(bounds.get_center().distance_to(frame_bounds.get_center()) < 1.0, "Master covered title is centered inside the frame")
	var font_size := float(title.get_theme_font_size("font_size"))
	var measured := title.get_theme_font("font").get_string_size(title.text, HORIZONTAL_ALIGNMENT_LEFT, -1, int(font_size))
	var ratio := measured.x / font_size
	var expected := clampf(minf(panel.size.x / ratio, panel.size.y) * .9, .1, maxf(panel.size.x, panel.size.y) * .8)
	check(is_equal_approx(title.scale.x * font_size, expected), "Master uses 90 percent fitting and its original 80 percent font cap")
	var source := preload("res://src/main/continuous_corners.gd").source(panel.get_theme_stylebox("panel"))
	check(is_equal_approx(source.bg_color.a, .5), "Master cover opacity is one half")
	check(title.get_theme_color("font_color") == Color.WHITE, "Master dark canvas uses white title")
	check(panel.get_node_or_null("HeaderBackground") == null, "Custom top badges and accent bars are absent")
	check(title.text_overrun_behavior == TextServer.OVERRUN_NO_TRIMMING, "Master fits the full title instead of adding ellipsis")
	var border: Line2D = panel.get_node("Border")
	check(border != null, "Master preview has a native border with fractional widths")
	check(source.border_width_left == 2, "Covered group retains master's two-pixel border")
	check(source.border_color == Color("#585b70"), "Master Mocha stage border color is reused")
	var branch_panel: Panel = overview._summaries[branch.get_instance_id()]
	var displayed := branch_panel.get_global_transform() * Rect2(Vector2.ZERO, branch_panel.size)
	check(displayed.is_equal_approx(branch.aabb), "Immediate branch geometry remains its actual node rectangle")
	check(not overview._summaries.has(deep.get_instance_id()), "Only the requested next layer is shown")
	check(StageObjectRegistry.capture(stage) == before, "Master visual port leaves persistent layout untouched")
	await RenderingServer.frame_post_draw
	root.get_texture().get_image().save_png("/tmp/pg-master-preview.png")
	frame.fill_color = Color("#89b4fa")
	await settle()
	check(title.get_theme_color("font_color") == Color.BLACK, "Master colorInvert uses black for an opaque bright group color")
	frame.fill_color = Color.TRANSPARENT
	app._apply_preferences("theme", "latte")
	await settle()
	check(title.get_theme_color("font_color") == Color.BLACK, "Master Latte canvas uses black title")
	source = preload("res://src/main/continuous_corners.gd").source(panel.get_theme_stylebox("panel"))
	check(source.border_color == Color("#acb0be"), "Master Latte stage border color is reused")
	app._apply_preferences("theme", "mocha")
	await settle()
	await click_world(frame.aabb.get_center(), true)
	check(frame._editing and frame.text_edit.has_focus(), "Native double click still edits the original group")
	frame.exit_edit_mode(false)
	await settle()
	await zoom_to(2.0)
	check(overview._summaries.is_empty(), "Zoom in restores the original view")
	app.queue_free()
	await process_frame
	print("MASTER_PREVIEW_VISUAL: " + ("PASS" if failures.is_empty() else str(failures)))
	quit(0 if failures.is_empty() else 1)
