export const keyboardLayout = [
  // 第一行: 数字和符号
  { row: 0, col: 0, code: "Backquote", label: "`", width: 1 },
  { row: 0, col: 1, code: "Digit1", label: "1", width: 1 },
  { row: 0, col: 2, code: "Digit2", label: "2", width: 1 },
  { row: 0, col: 3, code: "Digit3", label: "3", width: 1 },
  { row: 0, col: 4, code: "Digit4", label: "4", width: 1 },
  { row: 0, col: 5, code: "Digit5", label: "5", width: 1 },
  { row: 0, col: 6, code: "Digit6", label: "6", width: 1 },
  { row: 0, col: 7, code: "Digit7", label: "7", width: 1 },
  { row: 0, col: 8, code: "Digit8", label: "8", width: 1 },
  { row: 0, col: 9, code: "Digit9", label: "9", width: 1 },
  { row: 0, col: 10, code: "Digit0", label: "0", width: 1 },
  { row: 0, col: 11, code: "Minus", label: "-", width: 1 },
  { row: 0, col: 12, code: "Equal", label: "=", width: 1 },
  { row: 0, col: 13, code: "Backspace", label: "Delete", width: 2 },

  // 第二行: QWERTY
  { row: 1, col: 0, code: "Tab", label: "Tab", width: 1.5 },
  { row: 1, col: 1.5, code: "KeyQ", label: "Q", width: 1 },
  { row: 1, col: 2.5, code: "KeyW", label: "W", width: 1 },
  { row: 1, col: 3.5, code: "KeyE", label: "E", width: 1 },
  { row: 1, col: 4.5, code: "KeyR", label: "R", width: 1 },
  { row: 1, col: 5.5, code: "KeyT", label: "T", width: 1 },
  { row: 1, col: 6.5, code: "KeyY", label: "Y", width: 1 },
  { row: 1, col: 7.5, code: "KeyU", label: "U", width: 1 },
  { row: 1, col: 8.5, code: "KeyI", label: "I", width: 1 },
  { row: 1, col: 9.5, code: "KeyO", label: "O", width: 1 },
  { row: 1, col: 10.5, code: "KeyP", label: "P", width: 1 },
  { row: 1, col: 11.5, code: "BracketLeft", label: "[", width: 1 },
  { row: 1, col: 12.5, code: "BracketRight", label: "]", width: 1 },
  { row: 1, col: 13.5, code: "Backslash", label: "\\", width: 1.5 },

  // 第三行: ASDF
  { row: 2, col: 0, code: "CapsLock", label: "Caps Lock", width: 1.75 },
  { row: 2, col: 1.75, code: "KeyA", label: "A", width: 1 },
  { row: 2, col: 2.75, code: "KeyS", label: "S", width: 1 },
  { row: 2, col: 3.75, code: "KeyD", label: "D", width: 1 },
  { row: 2, col: 4.75, code: "KeyF", label: "F", width: 1 },
  { row: 2, col: 5.75, code: "KeyG", label: "G", width: 1 },
  { row: 2, col: 6.75, code: "KeyH", label: "H", width: 1 },
  { row: 2, col: 7.75, code: "KeyJ", label: "J", width: 1 },
  { row: 2, col: 8.75, code: "KeyK", label: "K", width: 1 },
  { row: 2, col: 9.75, code: "KeyL", label: "L", width: 1 },
  { row: 2, col: 10.75, code: "Semicolon", label: ";", width: 1 },
  { row: 2, col: 11.75, code: "Quote", label: "'", width: 1 },
  { row: 2, col: 12.75, code: "Enter", label: "Enter", width: 2.25 },

  // 第四行: ZXCV
  { row: 3, col: 0, code: "ShiftLeft", label: "Shift", width: 2.25 },
  { row: 3, col: 2.25, code: "KeyZ", label: "Z", width: 1 },
  { row: 3, col: 3.25, code: "KeyX", label: "X", width: 1 },
  { row: 3, col: 4.25, code: "KeyC", label: "C", width: 1 },
  { row: 3, col: 5.25, code: "KeyV", label: "V", width: 1 },
  { row: 3, col: 6.25, code: "KeyB", label: "B", width: 1 },
  { row: 3, col: 7.25, code: "KeyN", label: "N", width: 1 },
  { row: 3, col: 8.25, code: "KeyM", label: "M", width: 1 },
  { row: 3, col: 9.25, code: "Comma", label: ",", width: 1 },
  { row: 3, col: 10.25, code: "Period", label: ".", width: 1 },
  { row: 3, col: 11.25, code: "Slash", label: "/", width: 1 },
  { row: 3, col: 12.25, code: "ShiftRight", label: "Shift", width: 2.75 },

  // 第五行: 功能键
  { row: 4, col: 0, code: "ControlLeft", label: "Ctrl", width: 1.25 },
  { row: 4, col: 1.25, code: "MetaLeft", label: "Meta", width: 1.25 },
  { row: 4, col: 2.5, code: "AltLeft", label: "Alt", width: 1.25 },
  { row: 4, col: 3.75, code: "Space", label: "Space", width: 6.25 },
  { row: 4, col: 10, code: "AltRight", label: "Alt", width: 1.25 },
  { row: 4, col: 11.25, code: "MetaRight", label: "Meta", width: 1.25 },
  { row: 4, col: 12.5, code: "ControlRight", label: "Ctrl", width: 1.25 },
  { row: 4, col: 13.75, code: "ArrowLeft", label: "←", width: 1 },
  { row: 4, col: 14.75, code: "ArrowDown", label: "↓", width: 1 },
  { row: 4, col: 15.75, code: "ArrowRight", label: "→", width: 1 },
  { row: 3, col: 15.75, code: "ArrowUp", label: "↑", width: 1 },
];
