import fs from "fs";
import path from "path";

const src = path.join(process.cwd(), "./src");

// find all ts files in src
const files = fs.globSync("./src/**/*.ts", {
  exclude: ["**/node_modules/**", "**/*.d.ts", "**/index.ts"],
});

// generate code
const lines = [
  "// Auto-generated by scripts/barrel.ts",
  ...files.map((file) => {
    const relativePath = path.relative(src, file).replace(/\.ts$/, "");
    const importPath = `./${relativePath.replace(/\\/g, "/")}`;
    return `export * from "${importPath}";`;
  }),
];

// write to index.ts
const indexPath = path.join(src, "index.ts");
fs.writeFileSync(indexPath, lines.join("\n") + "\n");

console.log(`Generated ${indexPath} with ${files.length} exports.`);
