import {
  AlignStartVertical,
  AppWindow,
  AppWindowMac,
  ArrowDownNarrowWide,
  BatteryCharging,
  Blend,
  Bug,
  CaseSensitive,
  Columns4,
  Crosshair,
  Database,
  FileStack,
  Folder,
  Fullscreen,
  Gauge,
  Grab,
  Grip,
  Hand,
  HandMetal,
  HardDrive,
  HardDriveDownload,
  Hourglass,
  ImageMinus,
  ImageUpscale,
  Keyboard,
  Languages,
  LineSquiggle,
  ListCheck,
  ListCollapse,
  ListEnd,
  ListRestart,
  ListTree,
  Mouse,
  MousePointerClick,
  Move,
  Move3d,
  MoveHorizontal,
  MoveVertical,
  Presentation,
  Ratio,
  RefreshCcwDot,
  RotateCw,
  Rows4,
  Scaling,
  ScanEye,
  ScanText,
  Skull,
  Space,
  Spline,
  Square,
  SquareArrowDownRight,
  SquareArrowUpLeft,
  SquareM,
  Tag,
  TextCursorInput,
  Type,
  Undo,
  Ungroup,
  VenetianMask,
  WholeWord,
} from "lucide-react";

export const settingsIcons = {
  autoNamerTemplate: Tag,
  autoNamerSectionTemplate: Tag,
  autoSaveWhenClose: HardDriveDownload,
  autoSave: HardDrive,
  autoSaveInterval: Hourglass,
  autoBackup: Database,
  autoBackupInterval: Hourglass,
  autoBackupLimitCount: FileStack,
  autoBackupDraftPath: Folder,
  mouseRightDragBackground: MousePointerClick,
  mouseLeftMode: MousePointerClick,
  enableDragAutoAlign: AlignStartVertical,
  mouseWheelMode: Mouse,
  mouseWheelWithShiftMode: Mouse,
  mouseWheelWithCtrlMode: Mouse,
  mouseWheelWithAltMode: Mouse,
  doubleClickMiddleMouseButton: Mouse,
  mouseSideWheelMode: Grab,
  macMouseWheelIsSmoothed: Mouse,
  enableWindowsTouchPad: Hand,
  macTrackpadAndMouseWheelDifference: Hand,
  macTrackpadScaleSensitivity: HandMetal,
  allowMoveCameraByWSAD: Keyboard,
  cameraFollowsSelectedNodeOnArrowKeys: Crosshair,
  cameraKeyboardMoveReverse: Keyboard,
  moveAmplitude: Move,
  moveFriction: Move,
  scaleExponent: ScanEye,
  cameraResetViewPaddingRate: Fullscreen,
  scaleCameraByMouseLocation: ScanEye,
  cameraKeyboardScaleRate: ScanEye,
  rectangleSelectWhenRight: SquareArrowDownRight,
  rectangleSelectWhenLeft: SquareArrowUpLeft,
  textNodeStartEditMode: ListRestart,
  textNodeContentLineBreak: ListEnd,
  textNodeExitEditMode: ListCheck,
  textNodeSelectAllWhenStartEditByMouseClick: TextCursorInput,
  textNodeSelectAllWhenStartEditByKeyboard: TextCursorInput,
  allowAddCycleEdge: RotateCw,
  autoLayoutWhenTreeGenerate: ListTree,
  gamepadDeadzone: Skull,
  historySize: Undo,
  compressPastedImages: ImageMinus,
  maxPastedImageSize: ImageUpscale,
  autoRefreshStageByMouseAction: RefreshCcwDot,
  isPauseRenderWhenManipulateOvertime: Hourglass,
  renderOverTimeWhenNoManipulateTime: Hourglass,
  ignoreTextNodeTextRenderLessThanCameraScale: ScanText,
  textIntegerLocationAndSizeRender: WholeWord,
  isEnableEntityCollision: Ungroup,
  language: Languages,
  showTipsOnUI: AppWindow,
  useNativeTitleBar: AppWindowMac,
  isClassroomMode: Presentation,
  windowBackgroundAlpha: Blend,
  isRenderCenterPointer: Crosshair,
  showBackgroundHorizontalLines: Rows4,
  showBackgroundVerticalLines: Columns4,
  showBackgroundDots: Grip,
  showBackgroundCartesian: Move3d,
  enableTagTextNodesBigDisplay: Tag,
  showTextNodeBorder: Square,
  lineStyle: Spline,
  sectionBitTitleRenderType: SquareM,
  nodeDetailsPanel: AppWindow,
  alwaysShowDetails: ListCollapse,
  entityDetailsFontSize: CaseSensitive,
  entityDetailsLinesLimit: ArrowDownNarrowWide,
  entityDetailsWidthLimit: Space,
  showDebug: Bug,
  protectingPrivacy: VenetianMask,
  windowCollapsingWidth: MoveHorizontal,
  windowCollapsingHeight: MoveVertical,
  limitCameraInCycleSpace: Ratio,
  cameraCycleSpaceSizeX: Scaling,
  cameraCycleSpaceSizeY: Scaling,
  autoAdjustLineEndpointsByMouseTrack: LineSquiggle,
  enableRightClickConnect: MousePointerClick,
  isStealthModeEnabled: Crosshair,
  stealthModeScopeRadius: ScanEye,
  clearHistoryWhenManualSave: Undo,
  powerPreference: BatteryCharging,
  textResolution: Type,
  maxFps: Gauge,
  minFps: Gauge,
  mouseTrail: LineSquiggle,
  cadLikeSelection: Blend,
};
