name: "Canary"
on:
  push:
    branches:
      - godot

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.7
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/4.7.stable ~/.local/share/godot/export_templates/4.7.stable
      - name: Export
        run: |
          mkdir -v -p dist/web
          EXPORT_DIR="$(readlink -f dist)"
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 26
      - name: Deploy
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
